============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-8.4.2, pluggy-1.6.0
rootdir: /mnt/c/Users/user1/Desktop/Curso-CC3S2/Prueba_Entrada_CC3S2/seccion2_python_git
plugins: cov-6.3.0
collected 0 items / 1 error

==================================== ERRORS ====================================
______________________ ERROR collecting tests/test_app.py ______________________
ImportError while importing test module '/mnt/c/Users/user1/Desktop/Curso-CC3S2/Prueba_Entrada_CC3S2/seccion2_python_git/tests/test_app.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_app.py:2: in <module>
    from Prueba_Entrada_CC3S2.seccion2_python_git.app.app import summarize
E   ModuleNotFoundError: No module named 'Prueba_Entrada_CC3S2'
=========================== short test summary info ============================
ERROR tests/test_app.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.19s ===============================
